from abc import ABC, abstractmethod
from app.domain.entities.account import Account

class AccountRepository(ABC):
    @abstractmethod
    def get(self, account_id: str) -> Account | None: ...
    @abstractmethod
    def get_or_create(self, account_id: str) -> Account: ...
    @abstractmethod
    def save(self, account: Account) -> None: ...
    @abstractmethod
    def clear(self) -> None: ...