# Generated by Django 5.2.17 on 2026-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('withdraw', 'withdraw'), ('transfer', 'transfer')], max_length=10)),
                ('amount', models.IntegerField()),
                ('origin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
